export const GROUP_CATEGORY_ID = process.env.GROUP_CATEGORY_ID
export const GROUP_CONSOLE_TEXT_CHANNEL_ID =
  process.env.GROUP_CONSOLE_TEXT_CHANNEL_ID
export const GROUP_WAITING_VOICE_CHANNEL_ID =
  process.env.GROUP_WAITING_VOICE_CHANNEL_ID
